name: Preview Deployment
# Secure deployment of pull request artifacts
# https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
on:
  workflow_run:
    workflows: ["Continuous Integration"]
    types: [completed]

permissions:
  pull-requests: write

jobs:
  preview-deployment:
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.conclusion == 'success' && (
        github.event.workflow_run.event == 'pull_request' || (
          github.event.workflow_run.event == 'push' &&
          github.event.workflow_run.head_branch == 'main'
        )
      )
    env:
      IMAGE_REPO: ghcr.io/sbb-design-systems/sbb-angular/showcase-preview
      IMAGE_TAG: rev-${{ github.event.workflow_run.head_sha }}
    steps:
    - uses: actions/checkout@v3
    - run: rm package.json yarn.lock
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - run: npm i decompress@4.2.1
    - name: Download Artifacts
      id: artifacts
      uses: actions/github-script@v6
      with:
        script: |
          const decompress = require('decompress');
          const fs = require('fs');

          const artifactsResult = await github.request(context.payload.workflow_run.artifacts_url);
          const artifact = artifactsResult.data.artifacts.find((a) =>
            a.name.startsWith('showcase-artifact-')
          );
          if (artifact) {
            core.info(`Found artifact ${artifact.name}`);
            try {
              const outputPath = 'dist/releases/showcase';
              const artifact = await github.request(artifactEntry.archive_download_url);
              const zipResult = await decompress(Buffer.from(artifact.data), '.');
              fs.mkdirSync(outputPath, { recursive: true });
              const tgzResult = await decompress(result[0].path, outputPath, {
                map: (file) => {
                  file.path = file.path.replace(/^package\//, '');
                  return file;
                }
              })
            } catch (e) {
              console.error(`Failed to download and unzip ${artifact.name}`);
            }
          } else {
            core.info(`No artifact found`);
          }
    - name: "Docker: Build image"
      run: docker build -t $IMAGE_REPO:$IMAGE_TAG .
    - name: "Docker: Publish image"
      run: docker push $IMAGE_REPO:$IMAGE_TAG
    - name: Create PR comment
      uses: actions/github-script@v6
      with:
        script: |
          const artifactsResponse = await github.request(context.payload.workflow_run.artifacts_url);
          const showcaseArtifact = artifactsResponse.data.artifacts.find((a) =>
            a.name.startsWith('showcase-artifact-')
          );
          if (showcaseArtifact && context.payload.workflow_run.pull_requests.length) {
            const pullRequest = context.payload.workflow_run.pull_requests[0];

            const { data: fullPr } = await github.rest.pulls.get({
              pull_number: pullRequest.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
            });

            // Don't comment renovate bot PRs
            if (fullPr?.user?.login === 'sbb-angular-renovate[bot]') {
              return;
            }

            const previewBaseUrl = `https://sbb-angular-preview-pr${pullRequest.number}.app.sbb.ch`;
            let moduleUrl = '';
            if (fullPr?.title) {
              const moduleName = fullPr.title.match(/^.*\(angular\/(.*)\):/i)?.[1];
              if (moduleName) {
                moduleUrl = `${previewBaseUrl}/angular/components/${moduleName}/examples`;
              }
            }

            const createdAtDate = new Date(
              context.payload.workflow_run.created_at
            ).toLocaleString('de');
            github.rest.issues.createComment({
              issue_number: pullRequest.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Preview ready from ${
                pullRequest.head.sha
              } at ${createdAtDate}:\n- ${previewBaseUrl}${
                moduleUrl ? `\n- Examples link: ${moduleUrl}` : ''
              }`,
            });
          }
